"""Initial cocktail data, migrated from the old static script.js / ledger.js.

Used once, the first time the database is created, so the app starts with the
same menu the static site shipped with. After that, everything is managed
through the admin panel and lives in the database.
"""

COCKTAILS = [
    {"name": "Americano", "zh": "美国佬", "base": "Campari", "price": 58,
     "taste_note": "草本微苦 · 气泡轻盈 · 适合作为开场",
     "ingredients": ["30ml Campari", "30ml Red Vermouth", "Soda Water"]},
    {"name": "Aviation", "zh": "飞行", "base": "Gin", "price": 98,
     "taste_note": "紫罗兰花香 · 柑橘酸度 · 优雅而冷冽",
     "ingredients": ["45ml Gin", "15ml Luxardo", "15ml Lemon juice", "1 Bar spoon Violette Crème"]},
    {"name": "Bee’s Knees", "zh": "蜂膝", "base": "Gin", "price": 78,
     "taste_note": "蜂蜜柔甜 · 青柠明亮 · 金酒植物香",
     "ingredients": ["45ml Gin", "10ml Lime juice", "Enough Honey"]},
    {"name": "Black Russian", "zh": "黑俄罗斯", "base": "Vodka", "price": 78,
     "taste_note": "咖啡烘烤 · 酒体厚重 · 苦甜直接",
     "ingredients": ["50ml Vodka", "20ml Coffee Liqueur"]},
    {"name": "Bloody Mary", "zh": "血腥玛丽", "base": "Vodka", "price": 78,
     "taste_note": "番茄鲜咸 · 香料辛辣 · 复杂浓郁",
     "ingredients": ["45ml Vodka", "90ml Tomato juice", "15ml Lemon juice", "Tabasco", "Celery Salt", "Pepper"]},
    {"name": "Blood and Sand", "zh": "血与沙", "base": "Whiskey", "price": 98,
     "taste_note": "苏格兰烟麦 · 橙汁果香 · 樱桃与甜味美思交织",
     "ingredients": ["40ml Scotch Whiskey", "30ml Orange Juice", "15ml Cherry Liqueur", "10ml Sweet Vermouth"]},
    {"name": "Boulevardier", "zh": "花花公子", "base": "Whiskey", "price": 108,
     "taste_note": "橙皮苦香 · 谷物温暖 · 深沉圆润",
     "ingredients": ["45ml Rye Whiskey", "30ml Campari", "30ml Red Vermouth"]},
    {"name": "Cardinale", "zh": "卡迪纳尔", "base": "Gin", "price": 88,
     "taste_note": "干爽草本 · 苦橙清晰 · 利落克制",
     "ingredients": ["40ml Gin", "20ml Dry Vermouth", "10ml Campari"]},
    {"name": "Clover Club", "zh": "三叶草俱乐部", "base": "Gin", "price": 88,
     "taste_note": "覆盆子果香 · 绵密泡沫 · 酸甜轻盈",
     "ingredients": ["45ml Gin", "15ml Raspberry Syrup", "15ml Lemon juice", "Egg White"]},
    {"name": "Cosmopolitan", "zh": "大都会", "base": "Vodka", "price": 78,
     "taste_note": "蔓越莓酸甜 · 柑橘清爽 · 都市感",
     "ingredients": ["40ml Vodka Citron", "15ml Cointreau", "15ml Lime juice", "30ml Cranberry juice"]},
    {"name": "Cuba Libre", "zh": "自由古巴", "base": "Rum", "price": 68,
     "taste_note": "焦糖气泡 · 青柠清亮 · 轻松畅饮",
     "ingredients": ["50ml White Rum", "120ml Cola", "10ml Lime juice"]},
    {"name": "Daiquiri", "zh": "大吉利", "base": "Rum", "price": 68,
     "taste_note": "朗姆甘蔗香 · 青柠锐利 · 纯粹平衡",
     "ingredients": ["60ml White Rum", "20ml Lime juice", "2 Bar Spoons Sugar"]},
    {"name": "Dry Martini", "zh": "干马天尼", "base": "Gin", "price": 98,
     "taste_note": "极干净 · 杜松主导 · 冷冽而经典",
     "ingredients": ["Gin", "Vermouth"]},
    {"name": "Espresso Martini", "zh": "意式浓缩马天尼", "base": "Vodka", "price": 88,
     "taste_note": "浓缩咖啡 · 香草甜感 · 丝滑醒神",
     "ingredients": ["50ml Vodka", "30ml Kahlúa", "10ml Syrup", "1 Espresso"]},
    {"name": "French 75", "zh": "法式 75", "base": "Gin", "price": 108,
     "taste_note": "香槟气泡 · 柠檬明亮 · 轻快优雅",
     "ingredients": ["30ml Gin", "15ml Syrup", "15ml Lemon juice", "60ml Champagne"]},
    {"name": "French Martini", "zh": "法式马天尼", "base": "Vodka", "price": 78,
     "taste_note": "热带果香 · 覆盆子甜 · 柔顺讨喜",
     "ingredients": ["45ml Vodka", "15ml Raspberry Liqueur", "15ml Pineapple juice"]},
    {"name": "Garibaldi", "zh": "加里波第", "base": "Campari", "price": 68,
     "taste_note": "鲜橙绵密 · 苦甜平衡 · 阳光明亮",
     "ingredients": ["45ml Campari", "120ml Orange juice"]},
    {"name": "Gin Fizz", "zh": "金菲士", "base": "Gin", "price": 78,
     "taste_note": "柠檬酸爽 · 气泡活泼 · 干净轻盈",
     "ingredients": ["45ml Gin", "30ml Lemon juice", "10ml Syrup", "Soda Water"]},
    {"name": "Grand Margarita", "zh": "特级玛格丽特", "base": "Tequila", "price": 98,
     "taste_note": "龙舌兰植物香 · 柑橘饱满 · 酸爽",
     "ingredients": ["45ml Tequila", "30ml Cointreau", "15ml Lime juice"]},
    {"name": "Hemingway special", "zh": "海明威", "base": "Rum", "price": 88,
     "taste_note": "葡萄柚清苦 · 樱桃核香 · 干爽",
     "ingredients": ["60ml Rum", "40ml Grapefruit juice", "15ml Luxardo", "15ml Lime juice"]},
    {"name": "John Collins", "zh": "约翰·柯林斯", "base": "Gin", "price": 78,
     "taste_note": "柠檬气泡 · 杜松草本 · 清爽修长",
     "ingredients": ["45ml Gin", "30ml Lemon juice", "15ml Syrup", "Soda Water"]},
    {"name": "Last Word", "zh": "遗言", "base": "Gin", "price": 128,
     "taste_note": "草药浓郁 · 青柠锐利 · 四味精确平衡",
     "ingredients": ["22.5ml Gin", "22.5ml Green Chartreuses", "22.5ml Luxardo", "22.5ml Lime juice"]},
    {"name": "Long Island Iced Tea", "zh": "长岛冰茶", "base": "Mixed", "price": 108,
     "taste_note": "柑橘可乐 · 酒感强烈 · 甜爽",
     "ingredients": ["15ml Vodka", "15ml Tequila", "15ml White Rum", "15ml Gin", "15ml Cointreau", "25ml Lemon juice", "30ml Syrup", "Cola"]},
    {"name": "Manhattan", "zh": "曼哈顿", "base": "Whiskey", "price": 98,
     "taste_note": "黑麦辛香 · 香艾酒甜润 · 成熟深邃",
     "ingredients": ["50ml Rye Whiskey", "20ml Red Vermouth", "1 dash Angostura Bitters"]},
    {"name": "Margarita", "zh": "玛格丽特", "base": "Tequila", "price": 88,
     "taste_note": "青柠鲜明 · 龙舌兰矿物感 · 盐边提味",
     "ingredients": ["50ml Tequila", "20ml Cointreau", "15ml Lime juice"]},
    {"name": "Martinez", "zh": "马丁内斯", "base": "Gin", "price": 98,
     "taste_note": "草本甜润 · 樱桃核香 · 马天尼的前奏",
     "ingredients": ["45ml Gin", "45ml Red Vermouth", "1 Bar spoon Luxardo", "2 Dashes Orange Bitters"]},
    {"name": "Negroni", "zh": "尼格罗尼", "base": "Gin", "price": 88,
     "taste_note": "苦橙 · 草本 · 甜苦等量的永恒经典",
     "ingredients": ["30ml Gin", "30ml Campari", "30ml Red Vermouth"]},
    {"name": "New York Sour", "zh": "纽约酸", "base": "Whiskey", "price": 98,
     "taste_note": "威士忌酸甜 · 红酒单宁 · 层次分明",
     "ingredients": ["60ml Rye Whiskey", "22.5ml Syrup", "30ml Lemon juice", "Egg White", "15ml Red wine"]},
    {"name": "Old Fashioned", "zh": "古典", "base": "Whiskey", "price": 78,
     "taste_note": "木桶香草 · 苦精辛香 · 直接醇厚",
     "ingredients": ["45ml Rye Whiskey", "1 Sugar Cube", "1 Dash Bitter", "Water"]},
    {"name": "Pisco Sour", "zh": "皮斯科酸", "base": "Pisco", "price": 88,
     "taste_note": "葡萄蒸馏香 · 柑橘酸度 · 泡沫细腻",
     "ingredients": ["60ml Pisco", "30ml Lemon juice", "20ml Syrup", "Egg White"]},
    {"name": "Ramos Gin Fizz", "zh": "拉莫斯金菲士", "base": "Gin", "price": 98,
     "taste_note": "橙花奶香 · 绵密悠长 · 值得等待",
     "ingredients": ["别点我求你"]},
    {"name": "Sea Breeze", "zh": "海风", "base": "Vodka", "price": 68,
     "taste_note": "蔓越莓清酸 · 葡萄柚微苦 · 海风般轻快",
     "ingredients": ["40ml Vodka", "120ml Cranberry juice", "30ml Grapefruit juice"]},
    {"name": "Sex on the beach", "zh": "", "base": "Vodka", "price": 68,
     "taste_note": "桃子甜香 · 热带果汁 · 轻松易饮",
     "ingredients": ["40ml Vodka", "20ml Peach Schnapps", "40ml Orange juice", "40ml Cranberry juice"]},
    {"name": "Sidecar", "zh": "边车", "base": "Cognac", "price": 168,
     "taste_note": "干邑果干 · 橙香 · 酸度锋利而温暖",
     "ingredients": ["50ml Cognac", "20ml Cointreau", "20ml Lemon juice"]},
    {"name": "Tequila Sunrise", "zh": "龙舌兰日出", "base": "Tequila", "price": 78,
     "taste_note": "橙汁明亮 · 石榴甜美 · 渐层日出",
     "ingredients": ["45ml Tequila", "90ml Orange juice", "15ml Grenadine Syrup"]},
    {"name": "Trinidad Sour", "zh": "特立尼达酸", "base": "Bitters", "price": 158,
     "taste_note": "苦精香料 · 杏仁甜香 · 大胆而平衡",
     "ingredients": ["45ml Angostura Bitters", "30ml Orgeat Syrup", "22.5ml Lemon juice", "15ml Rye Whiskey"]},
    {"name": "Whiskey Sour", "zh": "威士忌酸", "base": "Whiskey", "price": 88,
     "taste_note": "柠檬酸甜 · 谷物温暖 · 泡沫柔滑",
     "ingredients": ["45ml Bourbon Whiskey", "25ml Lemon juice", "20ml Syrup", "Egg White"]},
    {"name": "White Lady", "zh": "", "base": "Gin", "price": 88,
     "taste_note": "柑橘清冽 · 杜松优雅 · 干净利落",
     "ingredients": ["40ml Gin", "30ml Cointreau", "20ml Lemon juice"]},
    {"name": "Mezcal Negroni", "zh": "梅斯卡尔尼格罗尼", "base": "Mezcal", "collection": "signature", "price": 128, "ledger_priority": 1,
     "taste_note": "烟熏龙舌兰 · 苦橙草本 · 深色而有张力",
     "ingredients": ["30ml Mezcal", "30ml Campari", "30ml Red Vermouth"]},
    {"name": "Perfect Manhattan", "zh": "完美曼哈顿", "base": "Whiskey", "price": 128, "ledger_priority": 2,
     "taste_note": "波本柔甜 · 黑麦辛香 · 干甜味美思的优雅平衡",
     "ingredients": ["30ml Bourbon Whiskey", "30ml Rye Whiskey", "15ml Dry Vermouth", "15ml Sweet Vermouth", "2 drops Bitters"]},
    {"name": "Sake Martini", "zh": "清酒马天尼", "base": "Gin", "collection": "signature", "price": 128, "ledger_priority": 3,
     "taste_note": "清酒米香 · 金酒冷冽 · 干味美思拉出细长尾韵",
     "ingredients": ["30ml Sake", "30ml Dry Gin", "10ml Dry Vermouth", "2 drops Bitters"]},
    {"name": "Lemon Cake", "zh": "柠檬蛋糕", "base": "Whiskey", "collection": "signature", "price": 128, "ledger_priority": 4,
     "taste_note": "柠檬蛋糕 · 奶油绵密 · 接骨木花香让尾韵轻盈",
     "ingredients": ["45ml Whiskey", "15ml Baileys", "15ml Elderflower Syrup", "20ml Lemon juice", "1 Whole Egg"]},
    {"name": "Tuxedo #2", "zh": "燕尾服", "base": "Gin", "price": 128, "ledger_priority": 5,
     "taste_note": "马天尼骨架 · 樱桃核香 · 橙苦精收出优雅尾韵",
     "ingredients": ["50ml Gin", "25ml Dry Vermouth", "5ml Luxardo", "1 dash Orange Bitters"]},
    {"name": "Bannockburn", "zh": "班诺克本", "base": "Whiskey", "price": 128, "ledger_priority": 6,
     "taste_note": "烟熏威士忌 · 番茄鲜感 · 青柠拉出清爽酸度",
     "ingredients": ["45ml Smoked Whiskey", "90ml Tomato Juice", "15ml Lime Juice", "5ml Sugar Syrup"]},
    {"name": "Yukiguni", "zh": "雪国", "base": "Other", "collection": "signature", "price": 128, "ledger_priority": 7,
     "taste_note": "蜜瓜清甜 · 黄瓜清爽 · 柑橘与桃子铺出雪感果香",
     "ingredients": ["Fresh Cucumber", "30ml Midori", "30ml Cointreau", "30ml Lemon Juice", "5ml Peach Syrup"]},
    {"name": "Baijiu Martini", "zh": "白酒马天尼", "base": "Gin", "collection": "signature", "price": 128, "ledger_priority": 8,
     "taste_note": "白酒芳香 · 金酒冷冽 · 白味美思带来干净收束",
     "ingredients": ["30ml Gin", "30ml Baijiu", "10ml White Vermouth", "2 drops Bitters"]},
]

# Fixed off-menu / bartender's-choice entry that always sits at the top of
# the private ledger's quick-order list. It is not a real recipe so it is
# never stored in the cocktails table.
OFF_MENU_ITEM = {"name": "Off-menu Special", "zh": "临时特调", "base": "Signature", "price": 128}


def seeded_cocktails():
    """Return seed rows with defaults filled in (collection, ledger_priority)."""
    rows = []
    for item in COCKTAILS:
        row = {
            "name": item["name"],
            "zh": item.get("zh", ""),
            "base": item.get("base", "Other"),
            "collection": item.get("collection", "classic"),
            "taste_note": item.get("taste_note", ""),
            "price": item.get("price", 0),
            "ingredients": item.get("ingredients", []),
            "ledger_priority": item.get("ledger_priority"),
        }
        rows.append(row)
    return rows
